namespace Incremental_source_generator_builder_pattern;

internal static class BuilderSourceEmitter
{
    internal static string GenerateBuilderAttribute(string builderAttributeName)
    {
        var vsb = new StringBuilder(512);
        vsb.Append("#nullable enable\n");
        vsb.Append("#pragma warning disable CA1813, CA1019, IDE0065, IDE0034, IDE0055\n\n");
        vsb.Append("using System;\n\n");
        vsb.Append($"namespace {Constants.GeneratorName};\n\n");
        vsb.Append(
            $"[System.CodeDom.Compiler.GeneratedCode(\"{Constants.GeneratorName}\", \"{Constants.GeneratorVersion}\")]\n");
        vsb.Append("[AttributeUsage(AttributeTargets.Class)]\n");
        vsb.Append($"public sealed class {builderAttributeName}(Type type) : Attribute\n{{\n");
        vsb.Append("    public Type TargetType { get; } = type;\n");
        vsb.Append("}\n");
        vsb.Append("#pragma warning restore CA1813, CA1019, IDE0065, IDE0034, IDE0055\n");

        return vsb.ToString();
    }
    
    
    internal static string GenerateDomainAssertionExtensions(string builderProduct)
    {
        var vsb = new StringBuilder(1024);
        vsb.Append("#pragma warning disable IDE0055, IDE0008\n");
        vsb.Append("#nullable enable\n\n");
        vsb.Append("using System;\n");
        vsb.Append("using System.Collections.Generic;\n\n");
        vsb.Append($"namespace {builderProduct};\n\n");
        vsb.Append($"[System.CodeDom.Compiler.GeneratedCode(\"{Constants.GeneratorName}\", \"{Constants.GeneratorVersion}\")]\n");
        vsb.Append($"public static class {Constants.DomainAssertionExtensions}\n");
        vsb.Append("{\n");
        vsb.Append("    /// <summary>\n");
        vsb.Append("    /// Adds a domain validation rule to be executed during the build phase.\n");
        vsb.Append("    /// </summary>\n");
        vsb.Append("    /// <typeparam name=\"TEntity\">The entity type the rule applies to.</typeparam>\n");
        vsb.Append($"    /// <param name=\"{Constants.DomainListName}\">The list of post-build domain rules.</param>\n");
        vsb.Append("    /// <param name=\"predicate\">A function that returns true when the entity violates a rule.</param>\n");
        vsb.Append("    /// <param name=\"errorMessage\">The error message that will be thrown if the rule fails.</param>\n");
        vsb.Append("    public static void AddDomainRule<TEntity>(\n");
        vsb.Append($"        this List<Action<TEntity>> {Constants.DomainListName},\n");
        vsb.Append("        Func<TEntity, bool> predicate,\n");
        vsb.Append("        string errorMessage)\n");
        vsb.Append("    {\n");
        vsb.Append($"        {Constants.DomainListName}.Add(e =>\n");
        vsb.Append("        {\n");
        vsb.Append("            if (predicate(e))\n");
        vsb.Append("                throw new InvalidOperationException(errorMessage);\n");
        vsb.Append("        });\n");
        vsb.Append("    }\n");
        vsb.Append("}\n");
        vsb.Append("#pragma warning restore IDE0055, IDE0008\n");

        return vsb.ToString();
    }
    
    internal static string GenerateBuilder(BuilderToGenerate builder)
    {
        var sb = new StringBuilder(8_192);

        AppendHeader(sb, builder);
        AppendFields(sb, builder);
        AppendWithMethods(sb, builder);
        AppendBuildMethod(sb, builder);
        // Add remainder

        return sb.ToString();
    }
    
    private static void AppendHeader(StringBuilder sb, BuilderToGenerate builder)
    {
        //#if DEBUG
        sb.Append("//----------------------------------------------------------------------------------\n");
        sb.Append("// <auto-generated>\n");
        sb.Append($"// This code was generated by BuilderGenerator at {DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss")} in {builder.ElapsedTime.ToString()}.\n");
        sb.Append("// </auto-generated>\n");
        sb.Append("//----------------------------------------------------------------------------------\n");
        //#endif
        sb.Append("#nullable enable\n");
        sb.Append("#pragma warning disable IDE0055, IDE0008\n\n");
        sb.Append("using System;\n");
        sb.Append("using System.Linq;\n");
        sb.Append("using System.Collections.Generic;\n");
        sb.Append("using BimServices.BuilderGenerator;\n");
    
        sb.Append($"namespace {builder.BuilderClassNamespace};\n\n");
        sb.Append($"[System.CodeDom.Compiler.GeneratedCode(\"{Constants.GeneratorName}\", \"{Constants.GeneratorVersion}\")]\n");
        sb.Append($"public partial class {builder.BuilderClassName}\n{{\n");
    }
    
    private static void AppendFields(StringBuilder sb, BuilderToGenerate builder)
    {
        sb.Append($"    private Func<{builder.TargetClassFullName}> {Constants.FactoryName} = () => new();\n");
        sb.Append($"    private readonly List<Action<{builder.TargetClassFullName}>> {Constants.DomainListName} = new();\n");

        foreach (var property in builder.Properties.AllProperties)
        { 
            var type = property.TypeName;
            var camelCase = char.ToLowerInvariant(property.Name[0]) + property.Name.Substring(1);
            sb.Append($"    private Func<{type}>? _{camelCase};\n");
        }

        sb.Append("\n");
    }
    
    private static void AppendWithMethods(StringBuilder sb, BuilderToGenerate builder)
    {
        foreach (var prop in builder.Properties.AllProperties)
        {
            var type = prop.TypeName;
            var name = prop.Name;
            var camelCase = char.ToLowerInvariant(name[0]) + name.Substring(1);
            
            sb.Append($"    public {builder.BuilderClassName} {Constants.WithMethodPrefix}{name}({type} @{camelCase})\n");
            sb.Append("    {\n");
            sb.Append($"        return {Constants.WithMethodPrefix}{name}(() => @{camelCase});\n");
            sb.Append("    }\n");
            sb.Append($"    public {builder.BuilderClassName} {Constants.WithMethodPrefix}{name}(Func<{type}> @{camelCase})\n");
            sb.Append("    {\n");
            sb.Append($"        _{camelCase} = @{camelCase};\n");
            sb.Append("        return this;\n    }\n\n");
        }
    }
    
    private static void AppendBuildMethod(StringBuilder sb, BuilderToGenerate builder)
    { 
        sb.Append($"    /// <summary> Returns configured of instance of the {builder.TargetClassFullName} entity </summary>\n");
        sb.Append($"    public {builder.TargetClassFullName} Build()\n");
        sb.Append("    {\n");
        sb.Append($"        {builder.TargetClassFullName} instance = {Constants.FactoryName}();\n\n");

        foreach (var prop in builder.Properties.Normal)
        {
            var name = prop.Name;
            var camelCase = char.ToLowerInvariant(name[0]) + name.Substring(1);

            sb.Append($"        if(_{camelCase} is not null)\n");
            sb.Append($"            instance.{name} = _{camelCase}.Invoke();\n\n");
        }

        foreach (var prop in builder.Properties.Collection)
        {
            var name = prop.Name;
            var camelCase = char.ToLowerInvariant(name[0]) + name.Substring(1);
            sb.Append($"        _{camelCase}?.Invoke()?\n");
            sb.Append("        .ToList()\n");
            sb.Append($"        .ForEach(item => instance.{name}.Add(item));\n\n");
        }

        sb.Append($"        {Constants.DomainListName}.ForEach(action => action(instance));\n\n");
        sb.Append("        return instance;\n}");
    }
}